# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0
  joint_a2: -0.7854
  joint_a3: 0.0
  joint_a4: 1.3962
  joint_a5: 0.0
  joint_a6: 0.75
  joint_a7: 0.0

#0.5, 1.5, 0.0, 2.0, 0.0, -1.25, -3.1415 for aruco
#0.6, -1.0, 0.0, 0.4, 0.0, -0.1, 3.14]   for aruco drittinfacc
#1.6, 1.5, 0.0, 2.0, 0.0, -1.25, -3.1415 for ball

#2.0, 1.5, -0.8, 2.0, -0.4, -1.0, 2.58 

#  joint_a1: 0.5
#  joint_a2: -0.7854
#  joint_a3: 0.0
#  joint_a4: 1.3962
#  joint_a5: 0.0
#  joint_a6: 0.6109
#  joint_a7: 0.0
